// must install "docker pipeline" and "junit" plugin

node {
    checkout scm
    def image = docker.image('maven:3.5.4-alpine')
    stage('Build') {
        image.inside('-v /root/.m2:/root/.m2') {
            sh 'mvn -B -DskipTests clean package'
        }
    }
    stage('Test') {
        try {
            image.inside('-v /root/.m2:/root/.m2') {
                sh 'mvn test'
            }
        } catch (e) {

        } finally {
            // post always
            junit 'target/surefire-reports/*.xml'
        }
    }
    stage('Manual Approval') {
        input(message: 'Lanjutkan ke tahap Deploy?', ok: 'Deploy')
    }
    stage('Deploy') {
        def sleepTime = 1 * 60 // 1 minute
        image.inside('-v /root/.m2:/root/.m2') {
            sh './jenkins/scripts/deliver.sh'
            archiveArtifacts artifacts: 'target/*.jar'
            sleep(sleepTime)
            echo 'Deployment complete'
        }
    }
}
